# Generated by Django 4.2.20 on 2025-04-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Educationalprogram',
            fields=[
                ('epId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='Разработка информационных систем для бизнеса', max_length=100)),
                ('Code', models.CharField(blank=True, default='09.03.04')),
            ],
        ),
    ]
