# Generated by Django 4.2.20 on 2025-04-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('facultyId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='Факультет социально-экономических и компьютерных наук', max_length=100)),
            ],
        ),
    ]
