# Generated by Django 4.2.20 on 2025-04-09 12:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('officers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filesnew',
            fields=[
                ('fileId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('DownloadDate', models.DateField(blank=True, default=datetime.date.today)),
                ('AdmissionYear', models.IntegerField(blank=True, default=2025)),
                ('DownloadOfficerId', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='officers.officer')),
            ],
        ),
    ]
