# Generated by Django 4.2.20 on 2025-04-09 15:10

from django.db import migrations, models
import filesnew.models


class Migration(migrations.Migration):

    dependencies = [
        ('filesnew', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesnew',
            name='File',
            field=models.FileField(blank=True, null=True, upload_to=filesnew.models.upload_to),
        ),
    ]
