# Generated by Django 4.2.20 on 2025-04-09 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesnew', '0002_filesnew_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filesnew',
            old_name='File',
            new_name='Filesnew',
        ),
    ]
