# Generated by Django 4.2.20 on 2025-04-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesnew', '0003_rename_file_filesnew_filesnew'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesnew',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
