# Generated by Django 4.2.20 on 2025-04-10 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesnew', '0004_filesnew_original_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesnew',
            name='original_name',
        ),
    ]
