# Generated by Django 4.2.20 on 2025-04-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesnew', '0005_remove_filesnew_original_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesnew',
            name='UniversityId',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
