# Generated by Django 4.2.20 on 2025-04-11 07:25

from django.db import migrations, models
import university.models


class Migration(migrations.Migration):

    dependencies = [
        ('filesnew', '0006_filesnew_universityid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesnew',
            name='UniversityId',
            field=models.IntegerField(blank=True, default=1, verbose_name=university.models.University),
        ),
    ]
