# Generated by Django 4.2.20 on 2025-04-11 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
        ('filesnew', '0007_alter_filesnew_universityid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesnew',
            name='UniversityId',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='university.university'),
        ),
    ]
