# Generated by Django 4.2.20 on 2025-04-11 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
        ('filesnew', '0008_alter_filesnew_universityid'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesnew',
            name='CityId',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='city.city'),
        ),
    ]
