# Generated by Django 4.2.20 on 2025-04-11 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesnew', '0009_filesnew_cityid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesnew',
            name='CityId',
        ),
    ]
