# Generated by Django 4.2.20 on 2025-04-13 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educationalprogram', '0001_initial'),
        ('filesnew', '0010_remove_filesnew_cityid'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesnew',
            name='EPId',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='educationalprogram.educationalprogram'),
        ),
    ]
