# Generated by Django 4.2.20 on 2025-04-14 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
        ('educationform', '0001_initial'),
        ('filesnew', '0011_filesnew_epid'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesnew',
            name='EFId',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='educationform.educationform'),
        ),
        migrations.AddField(
            model_name='filesnew',
            name='FacultyId',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='faculty.faculty'),
        ),
    ]
