# Generated by Django 4.2.20 on 2025-04-15 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('filesnew', '0012_filesnew_efid_filesnew_facultyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesnew',
            name='DownloadDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
