# Generated by Django 4.2.20 on 2025-04-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesnew', '0013_alter_filesnew_downloaddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesnew',
            name='Description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
