# Generated by Django 4.2.20 on 2025-04-12 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filesnew', '0010_remove_filesnew_cityid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predictfile',
            fields=[
                ('predictfileId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('PredictedFile', models.FileField(blank=True, null=True, upload_to='predicted_files/')),
                ('CreatedAt', models.DateField(blank=True, default=datetime.date.today)),
                ('MinExamScore', models.FloatField(blank=True, null=True)),
                ('SourceFiles', models.ManyToManyField(related_name='used_in_predictions', to='filesnew.filesnew')),
            ],
        ),
    ]
