# Generated by Django 4.2.20 on 2025-04-11 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('UniversityId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('CityId', models.ForeignKey(default='Пермь', on_delete=django.db.models.deletion.SET_DEFAULT, to='city.city')),
            ],
        ),
    ]
