# Generated by Django 4.2.20 on 2025-04-12 18:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
import emptyfile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
        ('officers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emptyfile',
            fields=[
                ('fileId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('DownloadDate', models.DateField(blank=True, default=datetime.date.today)),
                ('AdmissionYear', models.IntegerField(blank=True, default=2025)),
                ('Emptyfile', models.FileField(blank=True, null=True, upload_to=emptyfile.models.upload_to)),
                ('DownloadOfficerId', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='officers.officer')),
                ('UniversityId', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='university.university')),
            ],
        ),
    ]
