# Generated by Django 4.2.20 on 2025-04-14 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educationalprogram', '0001_initial'),
        ('educationform', '0001_initial'),
        ('faculty', '0001_initial'),
        ('emptyfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emptyfile',
            name='EFId',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='educationform.educationform'),
        ),
        migrations.AddField(
            model_name='emptyfile',
            name='EPId',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='educationalprogram.educationalprogram'),
        ),
        migrations.AddField(
            model_name='emptyfile',
            name='FacultyId',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='faculty.faculty'),
        ),
    ]
