# Generated by Django 4.2.20 on 2025-04-15 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emptyfile', '0002_emptyfile_efid_emptyfile_epid_emptyfile_facultyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emptyfile',
            name='DownloadDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
