# Generated by Django 4.2.20 on 2025-04-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emptyfile', '0003_alter_emptyfile_downloaddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='emptyfile',
            name='Description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
