# Generated by Django 4.2.20 on 2025-04-09 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='DownloadDate',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
