# Generated by Django 4.2.20 on 2025-04-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_downloaddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='DownloadOfficerId',
            field=models.IntegerField(default=1),
        ),
    ]
