# Generated by Django 4.2.20 on 2025-04-09 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0001_initial'),
        ('files', '0003_file_downloadofficerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='DownloadOfficerId',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='officers.officer'),
        ),
    ]
