# Generated by Django 4.2.20 on 2025-04-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_file_downloadofficerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='AdmissionYear',
            field=models.IntegerField(blank=True, default=2025),
        ),
    ]
