# Generated by Django 4.2.20 on 2025-04-18 10:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('educationalprogram', '0001_initial'),
        ('university', '0001_initial'),
        ('faculty', '0001_initial'),
        ('educationform', '0001_initial'),
        ('files', '0005_file_admissionyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='Description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='file',
            name='EFId',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='educationform.educationform'),
        ),
        migrations.AddField(
            model_name='file',
            name='EPId',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='educationalprogram.educationalprogram'),
        ),
        migrations.AddField(
            model_name='file',
            name='FacultyId',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='faculty.faculty'),
        ),
        migrations.AddField(
            model_name='file',
            name='File',
            field=models.FileField(blank=True, null=True, upload_to=files.models.upload_to),
        ),
        migrations.AddField(
            model_name='file',
            name='UniversityId',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='university.university'),
        ),
        migrations.AlterField(
            model_name='file',
            name='DownloadDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
